name: WolfyUtilities
api-version: 1.13
version: ${project.version}
author: WolfyScript
softdepend:
  - LWC
  - PlotSquared
  - WorldGuard
  - MythicMobs
  - BungeeChat

main: me.wolfyscript.utilities.main.Main

commands:
  wolfyutils:
    description: displays version of this plugin
  particle_effect:
    description: spawn/stop particle effects