name: WolfyUtilities
api-version: 1.13
version: 1.5.0.2
author: WolfyScript
softdepend:
  - LWC
  - PlotSquared
  - WorldGuard
  - MythicMobs
  - BungeeChat

main: me.wolfyscript.utilities.main.Main

commands:
  wolfyutils:
    description: displays version of this plugin
  spawn_particle:
    description: spawn particle effects