name: WolfyUtilities
api-version: 1.14
version: ${project.version}
author: WolfyScript
main: me.wolfyscript.utilities.main.WUPlugin

loadbefore:
  - ChatColor
  - ChatColor2
  - StackableItems
  - DiSky
  - EpicWorldGenerator

softdepend:
  - Magic
  - LWC
  - PlotSquared
  - WorldGuard
  - MythicMobs
  - MMOItems
  - BungeeChat
  - mcMMO
  - Oraxen
  - ItemsAdder
  - ExecutableItems

commands:
  wolfyutils:
    description: displays version of this plugin
  particle_effect:
    description: spawn particle effects
  particle_animation:
    description: spawn/stop particle animations
  wua:
    description: handles and executes ChatClickActions
  wui:
    description: handles and executes ChatInputs